name: Build and publish

on:
  push:
  pull_request:
  release:
    types:
      - published
      - edited
  schedule:
    - cron: '15 1 * * 6'

jobs:
  build-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: rumexcrispp
      buildx_platforms: linux/amd64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: ${{ github.event_name == 'release' || ((github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main') }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        if: ${{ github.event_name == 'release' || ((github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/main') }}
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/latex-docker:latest
          push: true
      
      - name: Update Docker Hub description
        if: ${{ github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          readme-filepath: README.md
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/latex-docker
