name: Build and publish

on:
  push:
    branches:
      - main
      - 'release/*'
      - '**'
  pull_request:
  release:
    types:
      - published
      - edited
  schedule:
    - cron: '15 1 * * 6'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  buildx_platforms: linux/amd64, linux/arm64

jobs:
  build-push:
    name: Build and push Docker image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      
      - name: Extract version label from Dockerfile
        id: extract_version
        run: |
          version=$(grep 'LABEL version=' docker/Dockerfile | cut -d'=' -f2 | tr -d ' "')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Determine Docker tags
        id: docker_tags
        run: |
          TAGS="testing"
          BRANCH_TAG=$(echo "${GITHUB_REF#refs/heads/}" | tr / -)
          TAGS="${TAGS},${BRANCH_TAG}"
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAGS="${TAGS},latest"
          fi
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            TAGS="${TAGS},${VERSION}"
          fi
          TAGS=$(echo "$TAGS" | tr ',' '\n' | awk '!seen[$0]++' | tr '\n' ',')
          TAGS=${TAGS%,}
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          labels: |
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}
            org.opencontainers.image.url=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=MIT
      
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.5.0
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: ${{ env.buildx_platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
